version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout                        
          - run:
      name: chmod permissions
      command: chmod +x ./gradlew         
           - run:
          name: Run Tests
          command: ./gradlew lint test

