version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}     
          
      - save_cache:
          paths:
            - ~/.gradle
                  
          - run:
      name: chmod permissions
      command: chmod +x ./gradlew         
           - run:
          name: Run Tests
          command: ./gradlew lint test

